health/urls.py
from django.urls import path

from . import views

app_name = 'health'
urlpatterns = [
    path('', views.home, name='home'),
    path('case/', views.case, name='case'),
    path('<str:symptom>/', views.diagnoses, name='diagnoses'),
    path('<str:diagnosis>/treatment/', views.treatment, name='treatment'),
     # Copied from docs; need review below:
    path('test/formwizard/', views.ContactWizard.as_view(views.ContactWizard.form_list), name='formwizard'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('health/', include('health.urls')),
]

health/models.py
from django.db import models

class Location(models.Model):
    location_text = models.CharField(max_length=200)
    def __str__(self):
        return self.location_text
    class Meta:
        ordering = ('location_text',)


class Symptom(models.Model):
    # Symptom
    symptom_text = models.CharField(max_length=200)
    locations = models.ManyToManyField(Location)
    def __str__(self):
        return self.symptom_text
    class Meta:
        ordering = ('symptom_text',)

class Diagnosis(models.Model):
    # Diagnosis
    diagnosis_text = models.CharField(max_length=200)
    # One diagnosis can link to many symptoms; one symptom can link to many diagnoses
    # i.e. many-to-many relationship
    symptoms = models.ManyToManyField(Symptom)
    def __str__(self):
        return self.diagnosis_text
    class Meta:
        ordering = ('diagnosis_text',)

class Treatment(models.Model):
    # Treatment
    treatment_text = models.CharField(max_length=2000)
    # One diagnosis can link to many treatments; one treatment can link to many diagnoses
    # i.e. many-to-many relationship
    diagnoses = models.ManyToManyField(Diagnosis)
    def __str__(self):
        return self.treatment_text
    class Meta:
        ordering = ('treatment_text',)

health/forms.py
from django import forms

class ContactForm1(forms.Form):
    subject = forms.CharField(max_length=100)
    sender = forms.EmailField()

class ContactForm2(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

health/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from formtools.wizard.views import SessionWizardView

import random

from .models import Symptom, Diagnosis
from . import forms

# FORMS = [("address", myapp.forms.AddressForm),
#          ("paytype", myapp.forms.PaymentChoiceForm),
#          ("cc", myapp.forms.CreditCardForm),
#          ("confirmation", myapp.forms.OrderForm)]
#
# TEMPLATES = {"address": "checkout/billingaddress.html",
#              "paytype": "checkout/paymentmethod.html",
#              "cc": "checkout/creditcard.html",
#              "confirmation": "checkout/confirmation.html"}

# Home page
def home(request):
    common_symptoms = Symptom.objects.all()[:5]
    context = { 'common_symptoms': common_symptoms }
    return render(request, 'health/home.html', context)

class ContactWizard(SessionWizardView):
    form_list = [forms.ContactForm1, forms.ContactForm2]
    def done(self, form_list, form_dict, **kwargs):
        # Do something here
        return HttpResponseRedirect('health/test.html')

# Diagnoses page
def diagnoses(request, symptom):
    # Check if symptom exists in database
    try:
        s = Symptom.objects.get(symptom_text__icontains=symptom)
    except Symptom.DoesNotExist:
        raise Http404("Symptom does not exist in system.")
    except Symptom.MultipleObjectsReturned:
        return many_symptoms_found(request, symptom)
    context = { 's': s }
    return render(request, 'health/diagnoses.html', context)
    # return HttpResponse('Diagnosis page')

# If search returns many symptoms
def many_symptoms_found(request, symptom):
    try:
        s = Symptom.objects.filter(symptom_text__icontains=symptom)
    except Symptom.DoesNotExist:
        raise Http404("Cannot find any symptoms.")
    return render(request, 'health/search_suggest.html', { 's': s })

# Treatment page
def treatment(request, diagnosis):
    # Check if diagnosis exists in database
    try:
        d = Diagnosis.objects.get(diagnosis_text=diagnosis)
    except Diagnosis.DoesNotExist:
        raise Http404("Diagnosis does not exist in system.")
    context = { 'd': d }
    return render(request, 'health/treatment.html', context)

# Generate a case
# Pick a random diagnosis, then pick 5 random symptoms
# of that diagnosis
def case(request):
    try:
        all_diagnoses = Diagnosis.objects.all()
    except all_diagnoses.DoesNotExist:
        raise Http404("Database is empty.")
    random_diagnosis = random.choice(all_diagnoses)
    symptoms = random_diagnosis.symptoms.all()
    random_symtoms = random.sample(list(symptoms), min(5, len(list(symptoms))))
    return render(request, 'health/case.html', { 'random_symtoms': random_symtoms })

health/templates/health/case.html
<!DOCTYPE html>

<html>

  <head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'health/style.css' %}">
    <title> Case study </title>
  </head>

  <body>
    <p> Case: </p>
    {% if random_symtoms %}
    <ul>
      {% for s in random_symtoms %}
        <li> {{ s.symptom_text }} </li>
      {% endfor %}
    </ul>
    {% endif %}
    <a href="{% url 'health:home' %}"> Return to homepage </a>
  </body>

</html>

health/templates/health/diagnoses.html
<!DOCTYPE html>
<html>

  <head>
    <title> {{ s.symptom_text }} </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'health/style.css' %}">
  </head>

  <body>
    <h2> Symptom: {{ s.symptom_text }} </h2>
    <hr>
    {% if s.diagnosis_set.all %}
    <p> Possible diagnoses: </p>
    <ul>
      {% for d in s.diagnosis_set.all %}
        <li> <a href="{% url 'health:treatment' d.diagnosis_text %}"> {{ d.diagnosis_text }} </a> </li>
      {% endfor %}
    </ul>
    {% else %}
      <p> Symptom has not been linked to any diagnosis in our database. </p>
    {% endif %}
    <a href="{% url 'health:home' %}"> Return to homepage </a>
  </body>

</html>

health/templates/health/home.html
<!DOCTYPE html>

<html>

  <head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'health/style.css' %}">
    <title> Homepage </title>
    <script>
      // Given user input, replace any white space with '-',
      // then append it to the home URL; go to URL
      function getURL_given_input() {
        var input = document.getElementById("url").value;
        var url = "{% url 'health:home' %}" + input.toLowerCase();
        location.href = url;
        return false;
      }
    </script>
  </head>

  <body>
    <h1> Welcome to our health app </h1>
    <hr>
    <p> Case study: <a href="{% url 'health:case' %}"> generate a case </a> </p>
    <hr>
    {% if error_message %}
      <p> <strong> {{ error_message }} </strong> </p>
    {% endif %}

    <form onSubmit="return getURL_given_input();">
      Enter symptom: <input type="text" name="url" id="url"> <input type="submit" value="Look for diagnoses">
    </form>

    {% if common_symptoms %}
      <p> Some common symptoms: </p>
      <ul>
      {% for symptom in common_symptoms %}
        <li><a href="{% url 'health:diagnoses' symptom.symptom_text %}"> {{ symptom.symptom_text }} </a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p> No symptom information saved in system. </p>
    {% endif %}
  </body>

</html>

health/templates/health/query.html
<!DOCTYPE html>

<html>

  <head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'health/style.css' %}">
    <title> Searching </title>
  </head>

  <body>
    <p> Do you want to add another symtom? </p>
  </body>

</html>

health/templates/health/test.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</p>
<form action="" method="post">{% csrf_token %}
  <table>
    {{ wizard.management_form }}
    {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            {{ form }}
        {% endfor %}
    {% else %}
        {{ wizard.form }}
    {% endif %}
  </table>
  {% if wizard.steps.prev %}
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
    <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
  {% endif %}
  <input type="submit" value="{% trans "submit" %}"/>
</form>
{% endblock %}

health/templates/health/treatment.html
<!DOCTYPE html>
<html>

  <head>
    <title> {{d.diagnosis_text}} </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'health/style.css' %}">
  </head>

  </body>
    <h2> {{ d.diagnosis_text }} </h2>
    <hr>
    {% if d.treatment_set.all %}
    <p> Treatment: </p>
    <ul>
      {% for t in d.treatment_set.all %}
        <li>{{ t.treatment_text }}</li>
      {% endfor %}
    </ul>
    {% else %}
      <p> Diagnosis has not been linked to any treatment in our database. </p>
    {% endif %}
    <a href="{% url 'health:home' %}"> Return to homepage </a>
  </body>

</html>